### ISSUE TITLE
请问，在MAC下如何使用？ 

### ISSUE THREAD

**Issue by jiangshan1225** [chenjiandongx/mmjpg#11]
无法运行啊，首先报错ASSII码， 然后报各种错误。

**Comment by chenjiandongx** [comment]
依赖安装了没有？

**Comment by jiangshan1225** [comment]
$ cd '/Users/Jason/Documents/GitHub/mzitu/' && '/usr/bin/pythonw'  '/Users/Jason/Documents/GitHub/mzitu/analysis.py'  && echo Exit status: $? && exit 1
  File "/Users/Jason/Documents/GitHub/mzitu/analysis.py", line 8
SyntaxError: Non-ASCII character '\xe5' in file /Users/Jason/Documents/GitHub/mzitu/analysis.py on line 8, but no encoding declared; see http://python.org/dev/peps/pep-0263/ for details

这个是报错信息呢，看不懂。。

基本上全部东西都安装好了呢

**Comment by chenjiandongx** [comment]
你是  Python2 是吧

**Comment by jiangshan1225** [comment]
Python 3.7.0 (v3.7.0:1bf9cc5093, Jun 26 2018, 23:26:24) 
[Clang 6.0 (clang-600.0.57)] on darwin
Type "copyright", "credits" or "license()" for more information.
>>>  
这个应该是3.7吧

**Comment by jiangshan1225** [comment]
Traceback (most recent call last):
  File "<pyshell#2>", line 1, in <module>
    python /Users/Jason/Documents/GitHub/mmjpg.py
NameError: name 'python' is not defined
>>>

**Comment by chenjiandongx** [comment]
1. git clone https://github.com/chenjiandongx/mmjpg.git
2. cd mmjpg
3. pip install -r requirements.txt
4. edit [mm_crawler.py](https://github.com/chenjiandongx/mmjpg/blob/master/mm_crawler.py#L19) DIR_PATH constant
5. python mm_crawler.py
