### ISSUE TITLE
跑出来的只有带名字的空文件夹，最后以报错终止程序

### ISSUE THREAD

**Issue by While-Shark** [chenjiandongx/mmjpg#3]
Traceback (most recent call last):
  File "E:\tools\mmjpg-master\mm_crawler.py", line 94, in <module>
    pool.map(urls_crawler, urls)
  File "C:\Python27\lib\multiprocessing\pool.py", line 251, in map
    return self.map_async(func, iterable, chunksize).get()
  File "C:\Python27\lib\multiprocessing\pool.py", line 567, in get
    raise self._value
IOError: [Errno 9] Bad file descriptor

报错信息如上

**Comment by chenjiandongx** [comment]
多进程问题 python2的参考https://github.com/chenjiandongx/mmjpg/issues/1试一下吧

**Comment by chenjiandongx** [comment]
多进程问题 python2的参考https://github.com/chenjiandongx/mmjpg/issues/1 试一下吧

**Comment by While-Shark** [comment]
好的，我试试

**Comment by chenjiandongx** [comment]
行得通吗？
